### ISSUE TITLE
FileNotFoundError: There is no file matching prefix last-* in C:\Users\birad\darts_logs\transformer0\checkpoints

### ISSUE THREAD

**Issue by Harish11999** [CapWidow/W-Transformer#1]
[Harish - Jupyter Notebook.pdf](https://github.com/CapWidow/W-Transformer/files/10040765/Harish.-.Jupyter.Notebook.pdf)

I'm unable overcome this error - "FileNotFoundError: **There is no file matching prefix last-*** in C:\Users\birad\darts_logs\transformer0\checkpoints".

How can I solve this error and get my results?
I have attached the pdf of my code currently using please suggest me the needful.

**Comment by CapWidow** [comment]
Hello, 

Sorry for the delay, I had this issue also and I am currenting modifying the code so this doesn't happen anymore but normally there is an easy way to solve it. If you see in the attached screenshot of you code, the checkpoint are save every 10 epochs but you are only running 3 epochs so try to : 
              -Increase the number of epoch to at least 10. 
              -Decrease the checkpoint step to less than 3.

Let me know if you still face this issue I will try my best to put the new code ASAP.

Léna 
<img width="1052" alt="Screenshot 2022-11-21 at 10 28 43" src="https://user-images.githubusercontent.com/57952001/202981285-e6fa0823-1bb1-455d-8242-e287fd38904d.png">

**Comment by Harish11999** [comment]
I changed them as you suggested but the same problem persists. The same error is occurring. Please modify the code and help me.

**Comment by CapWidow** [comment]
No problem, i finish tested it and push it. It will be done by the end of the week.

**Comment by Harish11999** [comment]
Thank you. I'll be waiting for your code. I request you to please make it ASAP.

**Comment by Harish11999** [comment]
Any updates?

**Comment by CapWidow** [comment]
Hello, 
I normally fixed the code, can you please try it and tell me if the issue is still there for me it's ok now. 
Sorry for the delay I am currently busy.

**Comment by Harish11999** [comment]
Thank you very much @CapWidow, the code is running completely, and thanks for taking the time and helping in your busy schedule.  
Please share your LinkedIn profile link with me. Thank you.

**Comment by CapWidow** [comment]
You´re welcome, here it is : https://www.linkedin.com/in/lenasasal.
